package ve.com.fml.view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.HashMap;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

import ve.com.fml.model.datasource.GlobalData;
import ve.com.fml.model.fuzzy.FuzzyDataMining;


public class EditDTWindow extends javax.swing.JDialog {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private javax.swing.JComboBox<String> classComboBox;
	private javax.swing.JLabel classLabel;
	/**
	 * Creates new form EditDTWindow
	 * @param isModal 
	 * @param topFrame 
	 */
	public EditDTWindow(JFrame topFrame, boolean isModal) {
		super(topFrame,isModal);
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		kTextField = new javax.swing.JTextField();
		kLabel1 = new javax.swing.JLabel();
		TitleLabel = new javax.swing.JLabel();
		jSeparator2 = new javax.swing.JSeparator();
		kTextField1 = new javax.swing.JTextField();
		kDefLabel = new javax.swing.JLabel();
		kDefLabel1 = new javax.swing.JLabel();
		jSeparator1 = new javax.swing.JSeparator();
		cancelButton = new javax.swing.JButton();
		saveButton = new javax.swing.JButton();
		kLabel = new javax.swing.JLabel();
		classLabel = new javax.swing.JLabel();
		classComboBox = new javax.swing.JComboBox<String>();
		final HashMap<String, Integer> nominalAtts =  GlobalData.getInstance().getFuzzyInstances().getNominalAttributes();
		classComboBox.addItem("Seleccione un atributo clase");
		for (String nomAttLabel : nominalAtts.keySet()) {
			classComboBox.addItem(nomAttLabel);
		}

		// setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("Configuración de Algoritmo");

		kLabel1.setText("Umbral de confianza para la poda:");

		TitleLabel.setText("Configuración de Árbol de Decisión Difuso");

		classLabel.setText("Selección de atributo clase:");

		kDefLabel.setText("(default = 2)");

		kDefLabel1.setText("(default = 0.25)");

		cancelButton.setText("Cancelar");
		cancelButton.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				dispose();
			}
		});

		saveButton.setText("Guardar");
		saveButton.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				if(classComboBox.getSelectedIndex() != 0){
					GlobalData.getInstance().getFuzzyInstances().setClassIndex(nominalAtts.get(classComboBox.getSelectedItem()));
					GlobalData.getInstance().setCurrentTechnique(FuzzyDataMining.MODEL_FUZZY_DT);
					HashMap<String, Object> options = new HashMap<String, Object>();
					if(!kTextField.getText().isEmpty())
						options.put("mno", kTextField.getText());
					else
						options.put("mno", "2");
					if(!kTextField1.getText().isEmpty())
						options.put("ctt", kTextField1.getText());
					else
						options.put("ctt", "0.25");
					GlobalData.getInstance().setConfiguredTechnique(options);
					dispose();
				}else{
					JOptionPane.showMessageDialog(EditDTWindow.this, "Debe seleccionar un atributo clase.");
				}
			}
		});


		kLabel.setText("Número mínimo de instancias por hoja:");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addContainerGap()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(TitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
								.addGroup(layout.createSequentialGroup()
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jSeparator2)
												.addComponent(jSeparator1)
												.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
														.addGap(0, 0, Short.MAX_VALUE)
														.addComponent(saveButton)
														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(cancelButton)))
														.addContainerGap())
														.addGroup(layout.createSequentialGroup()
																.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
																		.addComponent(kLabel1, javax.swing.GroupLayout.Alignment.LEADING)
																		.addComponent(kLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
																		.addComponent(classLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
																		.addGap(10, 10, 10)
																		.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
																				.addGroup(layout.createSequentialGroup()
																						.addComponent(kTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																						.addComponent(kDefLabel1))
																						.addGroup(layout.createSequentialGroup()
																								.addComponent(kTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
																								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																								.addComponent(kDefLabel))
																								.addComponent(classComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
																								.addGap(13, 23, Short.MAX_VALUE))))
				);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
						.addContainerGap()
						.addComponent(TitleLabel)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(classLabel)
								.addComponent(classComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(kLabel)
										.addComponent(kTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(kDefLabel))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(kLabel1)
												.addComponent(kTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(kDefLabel1))
												.addGap(17, 17, 17)
												.addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(cancelButton)
														.addComponent(saveButton))
														.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				);

		pack();
	}// </editor-fold>


	// Variables declaration - do not modify
	private javax.swing.JLabel TitleLabel;
	private javax.swing.JButton cancelButton;
	private javax.swing.JButton saveButton;
	private javax.swing.JSeparator jSeparator1;
	private javax.swing.JSeparator jSeparator2;
	private javax.swing.JLabel kDefLabel;
	private javax.swing.JLabel kDefLabel1;
	private javax.swing.JLabel kLabel;
	private javax.swing.JLabel kLabel1;
	private javax.swing.JTextField kTextField;
	private javax.swing.JTextField kTextField1;
	// End of variables declaration
}